services:
  product-svc:
    build:
      context: .
      target: dev
    container_name: product-svc
    ports:
      - 3000:3000
    restart: always
    command: npm run start:dev
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./src
          target: usr/src/app/src
        - action: rebuild
          path: package.json

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql_data:
